version: '3.7'
services:
  proyecto-hilos:
    build: .
    image: proyecto-hilos
    command: ["1", "2"]
    environment:
      CPU_LIMIT: ${CPU_LIMIT:-0.5}
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
